"""feat: agrego campo activo en tablas usuarios y roles

Revision ID: 63d2d05e9c72
Revises: 
Create Date: 2026-04-01 21:31:57.992180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d2d05e9c72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('rol_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
